
-- sql  주석 이렇게 쓴다 --


--여러줄 주석 
--ctrl + / 빠른주석 주석해제


SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;

--특정 COLUMN만 지정하고 싶으면
SELECT EMPLOYEE_ID , FIRST_NAME , EMAIL FROM EMPLOYEES;

-- 타입 문자 , 날짜는 왼쪽,숫자는 오른쪽

SELECT HIRE_DATE, LAST_NAME, EMPLOYEE_ID FROM EMPLOYEES;    

--숫자컬럼은 * / + - 로 연산이 됩니다
SELECT FIRST_NAME , SALARY, SALARY + 10000 , SALARY+SALARY*0.1 FROM EMPLOYEES;

-- NULL 값 - DEPARTMENT_ID 가 FK이다
SELECT COMMISSION_PCT, DEPARTMENT_ID FROM EMPLOYEES;

--COLUMN ALIAS(별칭)AS -> ~~ AS 없어도되지만 웬만하면 붙이자 , 띄어쓰기를 쓸거면 ""로 묶어주기
SELECT FIRST_NAME AS 이름 , SALARY 급여, SALARY + SALARY*0.1 AS"최종 급여" FROM EMPLOYEES;

--문자열연결(더하기)
SELECT '이렇게 표현해요' FROM EMPLOYEES;
SELECT FIRST_NAME || ' ' || LAST_NAME ||' ''님의 급여는 ' || SALARY || '$입니다' AS SALARY FROM EMPLOYEES;

--DISTINCT키워드 (중복제거)
SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;

SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

SELECT DISTINCT FIRST_NAME ,LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES; --세개의 COLUMN 기준으로 중복 되는행 X

--ROWID(데이터의 주소), ROWNUM(조회된 번호)


SELECT EMPLOYEE_ID, FIRST_NAME, ROWID, ROWNUM FROM EMPLOYEES;

