--DDL문장 (트랜잭션이 없습니다)
--CREATE , ALTER ,DROP 문이 있습니다

DROP TABLE DEPTS ; -- DEPTS삭제
CREATE TABLE DEPTS (
    DEPT_NO NUMBER(2), --숫자 2자리
    DEPT_NAME VARCHAR2(30) , --30BYTE 크기 (한글은 15글자 , 숫자 OR영어는 30글자)
    DEPT_YN CHAR(1), --고정문자 1BYTE (VARCHAR2로 대체가능)
    DEPT_DATE DATE, --날짜 
    DEPT_BONUS NUMBER(10, 2), --숫자 10자리 ,소수점은 2자리까지 저장
    DEPT_CONTENT LONG --2기가 가변문자열(VARCHAR2 보다 더 큰 문자열)   
);

DESC DEPTS;

INSERT INTO DEPTS VALUES (99,'HELLO','Y',SYSDATE,3.14,'HELLO WORLD, HI~~');
INSERT INTO DEPTS VALUES (100,'HELLO','N',SYSDATE,3.14,'BYE~'); --DEPT_NO 초과
INSERT INTO DEPTS VALUES (1,'HELLO','가',SYSDATE,3.14,'BYE~'); --CHAR(1) 초과 (한글은 2BYTE)

SELECT * FROM DEPTS;
-----------------------------------------------
--테이블 구조 변경 ALTER

--컬럼추가 ADD
ALTER TABLE DEPTS ADD (DEPT_COUNT NUMBER(3));
INSERT INTO DEPTS(EMP_COUNT) VALUES(100);
DESC DEPTS;
DELETE FROM DEPTS(SELECT * FROM DEPTS WHERE DEPT_NO IS NULL);
SELECT * FROM DEPTS;

--컬럼명칭 변경 RENAME
ALTER TABLE DEPTS RENAME COLUMN DEPT_COUNT TO EMP_COUNT; --> DEPT_COUNT ->EMP_COUNT로 변경

DESC DEPTS;

--컬럼 수정(크기)MODIFY
ALTER TABLE DEPTS MODIFY (EMP_COUNT NUMBER(10) ); -- EMP_COUNT컬럼의 타입을 변경
DESC DEPTS;

ALTER TABLE DEPTS MODIFY (EMP_COUNT NUMBER(2)); -- EMP_COUNT컬럼의 타입을 변경
DESC DEPTS;

ALTER TABLE DEPTS MODIFY (DEPT_NAME VARCHAR2(1)); --기존 데이터가 변경할 크기를 넘어가는 경우,변경불가

SELECT * FROM DEPTS;

--컬럼 삭제 (DROP COLUMN)
ALTER TABLE DEPTS DROP COLUMN EMP_COUNT ;

DROP TABLE DEPTS;
DROP TABLE DEPARTMENTS ; -- 제약조건이 있어서 삭제가 안된다 (CASCADE 쓰면가능)

-----------------------------------------------

CREATE TABLE DEPT2(
            DEPT_NO NUMBER(3),
            DEPT_NAME VARCHAR2(15),
            LOCA_NUMBER NUMBER(4),
            DEPT_GENDER CHAR(1),
            REG_DATE DATE,
            DEPT_BONUS NUMBER(10,5)
);

INSERT INTO DEPT2 VALUES(999, '풀었다' , 9999 , 'M',SYSDATE , 3.14159);
SELECT * FROM DEPT2;