----연습문제문제 1.
--사원 테이블에서 JOB_ID별 사원 수를 구하세요.
--사원 테이블에서 JOB_ID별 월급의 평균을 구하세요. 월급의 평균 순으로 내림차순 정렬하세요


SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE;

SELECT JOB_ID ,
        COUNT(*) AS 사원수 ,
        AVG(SALARY) AS 급여평균 
FROM EMPLOYEES 
GROUP BY JOB_ID 
ORDER BY AVG(SALARY) DESC;

SELECT JOB_ID, AVG(SALARY) FROM EMPLOYEES GROUP BY CUBE(JOB_ID) ORDER BY(AVG(SALARY)) DESC;
--문제 2.
--사원 테이블에서 입사 년도 별 사원 수를 구하세요.
SELECT SUBSTR(HIRE_DATE, 1, 2) ||'년도' ,COUNT(*) FROM EMPLOYEES GROUP BY SUBSTR(HIRE_DATE,1,2) ORDER BY SUBSTR(HIRE_DATE,1,2);

SELECT TO_CHAR(HIRE_DATE , 'YY') AS 입사년도, COUNT(*) AS 사원수
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'YY');

--문제 3.
--급여가 1000 이상인 사원들의 부서별 평균 급여를 출력하세요. 단 부서 평균 급여가 2000이상인 부서만 출력

SELECT DEPARTMENT_ID ,AVG(SALARY)
FROM EMPLOYEES 
WHERE SALARY>=1000 
GROUP BY(DEPARTMENT_ID)
HAVING AVG(SALARY) >= 2000
ORDER BY DEPARTMENT_ID;
--문제 4.
--사원 테이블에서 commission_pct(커미션) 컬럼이 null이 아닌 사람들의
--department_id(부서별) salary(월급)의 평균, 합계, count를 구합니다.
--조건 1) 월급의 평균은 커미션을 적용시킨 월급입니다.
--조건 2) 평균은 소수 둘째 자리에서 절삭
SELECT DEPARTMENT_ID,
       TRUNC( AVG(SALARY+SALARY*COMMISSION_PCT),2),
        SUM(SALARY+SALARY*COMMISSION_PCT),
        COUNT(DEPARTMENT_ID) 
FROM EMPLOYEES 
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY DEPARTMENT_ID;

--5
SELECT  DECODE(GROUPING(JOB_ID),1,'합계', JOB_ID) ,SUM(SALARY) 
FROM EMPLOYEES
GROUP BY ROLLUP(JOB_ID);

--6
SELECT  DECODE(GROUPING(DEPARTMENT_ID) ,1,'합계',DEPARTMENT_ID),
        DECODE(GROUPING(JOB_ID),1,'소계',JOB_ID ),
        COUNT(*) AS TOTAL,
        SUM(SALARY)
      
FROM EMPLOYEES
GROUP BY ROLLUP (DEPARTMENT_ID , JOB_ID)
ORDER BY SUM(SALARY);

