--문자열 다루기 함수 LOWER, UPPER, INITCAP

SELECT 'abcDEF', LOWER('abcDEF'), UPPER('abcDEF'),INITCAP('abcDEF') FROM DUAL;
SELECT FIRST_NAME , LOWER(FIRST_NAME),UPPER(FIRST_NAME), INITCAP(FIRST_NAME) FROM EMPLOYEES;

--LENGTH - 길이 , INSTR - 문자열찾기 , CONCAT - 문자열붙이기
SELECT FIRST_NAME , LENGTH(FIRST_NAME), INSTR(FIRST_NAME,'a')FROM EMPLOYEES;

--SUBSTR(COLUMN,시작인덱스,자를문자갯수) - 문자열자르기 , COCNAT - 문자열붙이기
SELECT FIRST_NAME, SUBSTR(FIRST_NAME , 1 ,2) , SUBSTR(FIRST_NAME ,3 ) FROM EMPLOYEES;

-- CONCAT(FIRST_NAME , LAST_NAME) FROM EMPLOYEES;
SELECT CONCAT(FIRST_NAME , LAST_NAME), FIRST_NAME || LAST_NAME FROM EMPLOYEES; --두개가 같다

-- LPAD -왼쪽공백을 특정 값으로 채움, RPAD
SELECT LPAD('ABC',10,'*')FROM DUAL;

SELECT RPAD(FIRST_NAME, 10, '-'),LPAD(FIRST_NAME,10,'-')FROM EMPLOYEES; 

--TRIM - 양쪽공백제거 , LTRIM,RTRIM
SELECT TRIM(' HELLO WORLD ') , LTRIM(' HELLO WORLD ') , RTRIM(' HELLO WORLD ') FROM DUAL;

SELECT LTRIM('HELLO WORLD', 'HE' ) FROM DUAL;--왼쪽에서 처음발견된 HE를 삭제 

--REPLACE - 특정 문자를 변경
SELECT REPLACE('피카츄 라이츄 파이리 꼬북이','파이리','리자드') AS 변경값 FROM DUAL;

--my dream is hello world 
--hello 를 '헬로'
SELECT REPLACE(REPLACE('my dream is hello world','hello','헬로'),' ','') FROM DUAL;


